

const BUILDING_TYPE_CONVERSIONS = {
    "Residence Hall/Dormitory": "college_university",
    "College/University": "college_university",
    "Performing Arts": "assembly",
    "Parking": "storage",
    "Retail Store": "retail",
    "Multifamily Housing": "multifamily_housing",
    "Mixed Use Property": "office",
    "Manufacturing/Industrial Plant": "manufacturing_industrial",
    "Office": "office",
    "Urgent Care/Clinic/Other Outpatient": "healthcare",
    "Strip Mall": "retail",
    "Hotel": "lodging",
    "Enclosed Mall": "retail",
    "Other - Lodging/Residential": "lodging",
    "Hospital (General Medical & Surgical)": "healthcare",
    "Self-Storage Facility": "storage",
    "K-12 School": "education",
    "Other": "office",
    "Repair Services (Vehicle, Shoe, Locksmith, etc.)": "services",
    "Other - Mall": "retail",
    "Other - Utility": "storage",
    "Pre-school/Daycare": "education",
    "Other - Education": "education",
    "Senior Care Community": "multifamily_housing",
    "Distribution Center": "services",
    "Worship Facility": "assembly",
    "Bar/Nightclub": "services",
    "Laboratory": "technology_science",
    "Non-Refrigerated Warehouse": "storage",
    "Movie Theater": "assembly",
    "Other - Services": "assembly",
    "Medical Office": "office",
    "Financial Office": "office",
    "Supermarket/Grocery Store": "services",
    "Other - Technology/Science": "technology_science",
    "Energy/Power Station": "manufacturing_industrial",
    "Other - Specialty Hospital": "healthcare",
    "Other - Recreation": "assembly",
    "Museum": "assembly",
    "Social/Meeting Hall": "assembly",
    "Senior Living Community": "lodging",
    "Adult Education": "education",
    "Restaurant": "services",
    "Other - Entertainment/Public Assembly": "assembly",
    "Courthouse": "assembly",
    "Residential Care Facility": "lodging",
    "Library": "assembly",
    "Fire Station": "assembly",
    "Police Station": "assembly",
    "Other - Public Services": "assembly",
    "Fitness Center/Health Club/Gym": "assembly",
    "Stadium (Open)": "assembly",
    "Ambulatory Surgical Center": "healthcare",
    "Wholesale Club/Supercenter": "services",
    "Other - Stadium": "assembly",
    "Indoor Arena": "assembly",
    "Ice/Curling Rink": "assembly",
    "Single Family Home": "multifamily_housing",
    "Food Service": "services",
    "ACTIVITY/SOCIAL CENTER": "assembly",
    "ADMINISTRATIVE BLDG": "office",
    "Apartment": "multifamily_housing",
    "Apartment Property / APT 100+ UNITS": "multifamily_housing",
    "APT 100+ UNITS": "multifamily_housing",
    "APT 31-99 UNITS": "multifamily_housing",
    "APT 7-30 UNITS": "multifamily_housing",
    "APT SUBSIDIZED HOUSING": "multifamily_housing",
    "ATHLETIC FACILITY": "assembly",
    "AUDITORIUM / SPORT CTR": "assembly",
    "AUDITORIUM / THEATER": "assembly",
    "BOST REDEVELOP AUTH": "assembly",
    "BOSTON HOUSING AUTH": "assembly",
    "CHARITABLE ORGANIZTN": "assembly",
    "CHURCH, SYNAGOGUE": "assembly",
    "CITY OF BOSTON": "assembly",
    "CO-OP APARTMENT": "multifamily_housing",
    "COLD STORAGE WAREHOUSE": "storage",
    "COLLEGE": "college_university",
    "COM MULTI-USE": "assembly",
    "COMM CONDO": "assembly",
    "CONDO MAIN": "multifamily_housing",
    "ELDERLY HOME": "lodging",
    "EXEMPT 121A PROPERTY": "office",
    "FOOD PROCESS PLANT": "manufacturing_industrial",
    "HEALTH CLUB": "assembly",
    "HOSPITAL": "healthcare",
    "HOTEL/LODGING": "lodging",
    "INDUSTRIAL LOFT": "manufacturing_industrial",
    "LIGHT MFG / R & D": "technology_science",
    "MEDICAL CLINIC": "healthcare",
    "MOTEL": "lodging",
    "NURSING HOME": "lodging",
    "OFFICE 1-2 STORY": "office",
    "OFFICE 3-9 STORY": "office",
    "Office Bldg": "office",
    "OFFICE BUILDING": "office",
    "OFFICE CONDO": "office",
    "OFFICE/ADMINISTR BLDG": "office",
    "OFFICE/INDUSTRIAL USE": "office",
    "OLD MANUFACTURING": "storage",
    "OTHER EXEMPT BLDG": "office",
    "PARKING GARAGE": "storage",
    "PARKING LOT": "storage",
    "PRIV SCHOOL /COLLEGE": "college_university",
    "RADIO TV STUDIO": "services",
    "RECREATION BUILDING": "assembly",
    "REHAB/COVALES FACILITY": "assembly",
    "RELIGIOUS ORGANIZATN": "assembly",
    "REPAIR GARAGE": "services",
    "RES/COMMERCIAL USE": "multifamily_housing",
    "RETAIL USE": "retail",
    "RETAIL/OFFICE": "retail",
    "RETAIL/WHLSALE/SERVICE": "retail",
    "ROOMING HOUSE": "lodging",
    "SCHOOL": "education",
    "SCHOOL (TAXABLE)": "education",
    "SELF STORAGE WAREHOUSE": "storage",
    "SHOPPING CENTER": "retail",
    "SHOWROOM": "assembly",
    "SUBTERRANEAN GARAGE": "storage",
    "SUPERMARKET": "services",
    "TENNIS/ RACQUET CLUB": "assembly",
    "TRAINING FACILITY": "assembly",
    "U.S. GOVERNMENT": "office",
    "VACANT LAND": "office",
    "WAREHOUSE": "storage",

}


const convertBuildingType = (input) => {
    if (input in BUILDING_TYPE_CONVERSIONS) {
        return BUILDING_TYPE_CONVERSIONS[input]
    }
    else {
        return "office"
    }
}

export default convertBuildingType